FROM nvcr.io/nvidia/pytorch:22.12-py3

WORKDIR /workspace/
ENV PYTHONPATH /workspace/
COPY requirements.txt /workspace/
COPY . /workspace

RUN pip install --no-cache-dir -r /workspace/requirements.txt
RUN pip install bitsandbytes --upgrade
RUN pip install torch -U
RUN pip install vllm>=0.1.4 
RUN pip uninstall transformer-engine -y
